USE RecursosHumanos

-- TOP EXIBE UMA PARTE DOS REGISTROS DA TABELA,
-- EM QUANTIDADE OU EM PORCENTAGEM.

SELECT  TOP 3 * FROM FUNCIONARIO
select nome, max(salario) from funcionario
SELECT top 3  NOME, SALARIO FROM FUNCIONARIO
order by salario desc


SELECT TOP 1 NOME,SALARIO FROM FUNCIONARIO
ORDER BY SALARIO 

SELECT TOP 1 NOME,SALARIO FROM FUNCIONARIO



SELECT SUM(SALARIO) FROM FUNCIONARIO

select top 20   * from funcionario